version: '3'

services:
  salesplatform:
    image: ${DOCKER_REGISTRY-}salesplatform
    build:
      context: .
      dockerfile: SalesPlatform/Dockerfile
    ports:
      - 32000:8080
      - 32001:8081

  salesplatform_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespswd
      - POSTGRES_DB=SalesPlatformDb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  salesplatform_ui:
    build: 
        context: ./ui
        dockerfile: Dockerfile
    ports:
      - 5173:5173  # Map container port 5173 to host port 5173
    volumes:
      - ./ui:/app  # Mount current directory to /app in container
    environment:
      NODE_ENV: development

  db_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: s@s.dk
      PGADMIN_DEFAULT_PASSWORD: s@s.dk
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_data: {}
  pgadmin-data: {}